#!/usr/bin/with-contenv bash

# permissions
chown -R abc:abc \
        /app \
        /archive \
        /config \
        /opt

if [[ ! -d /config/var ]]
then
  mv /opt/${COMPANY_NAME}/mediaserver/var /config/var
fi

if [[ ! -h /opt/${COMPANY_NAME}/mediaserver/var ]]
then
  rm -rf /opt/${COMPANY_NAME}/mediaserver/var
  ln -s /config/var /opt/${COMPANY_NAME}/mediaserver/var
fi

if [[ ! -d /config/etc ]]
then
  mv /opt/${COMPANY_NAME}/mediaserver/etc /config/etc
fi

if [[ ! -h /opt/${COMPANY_NAME}/mediaserver/etc ]]
then
  rm -rf /opt/${COMPANY_NAME}/mediaserver/etc
  ln -s /config/etc /opt/${COMPANY_NAME}/mediaserver/etc
fi
